// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from './types'; // Assuming this import is correct

const SUPABASE_URL = "https://othjveclqmzlrbwqjkog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90aGp2ZWNscW16bHJid3Fqa29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODIyNTQsImV4cCI6MjA3MDY1ODI1NH0.4yBn9--bwHSTupKykDJn_LXciYO83-hzva2664kX6Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// This function safely instantiates the browser client.
export const createClientBrowser = () => {
  // Define a storage adapter. On the server, this will be undefined/null,
  // which prevents the crash, allowing Supabase to fall back gracefully.
  const browserStorage = (typeof window !== 'undefined' && window.localStorage) 
    ? window.localStorage 
    : undefined; // Or null, depending on desired strictness

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      // Pass the conditionally defined storage variable
      storage: browserStorage, 
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}